// <auto-generated />
using System;
using DotNetCoreMovies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace RazorPageDotnetCore.Migrations
{
    [DbContext(typeof(DotNetCoreMoviesContext))]
    partial class DotNetCoreMoviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("DotNetCoreMovies.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Genre")
                        .IsConcurrencyToken();

                    b.Property<string>("MovieName")
                        .IsConcurrencyToken();

                    b.Property<decimal>("Price")
                        .IsConcurrencyToken()
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating");

                    b.Property<DateTime>("ReleaseDate")
                        .IsConcurrencyToken();

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
